import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import {
  Push,
  PushToken
} from '@ionic/cloud-angular';
import { Http, Headers } from '@angular/http';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  icons: string[];
  eventSummary: string[];
  eventTime: string[];
  imageThumbnail: string[];
  items: Array<{eventSummary: string, eventTime: string, icons: string, imageThumbnail:string}>;

  constructor(public navCtrl: NavController, public push: Push, public http: Http) {
    var app = document.URL.indexOf( 'http://' ) === -1 && document.URL.indexOf( 'https://' ) === -1;
    if ( app ) {
        //we are running on a device
        this.registerForPush();
    } 

    //setting up sample newsfeed just for a mockup
    this.eventSummary = ["Here's an example of a transaction", "Person 1 did something",
    "Person 2 requested money", "Someone did a chore"]
    this.eventTime = ["45m","2h","1d","2d"]
    this.icons = ["thumbs-up"]
    this.imageThumbnail = ["assets/img/imgPlaceHolder.png"]

    this.items = []
    for (let i = 0; i < this.eventSummary.length; i++) {
      this.items.push({
        eventSummary: this.eventSummary[i],
        eventTime: this.eventTime[i],
        imageThumbnail: this.imageThumbnail[0],
        icons: this.icons[0]
      })
    }

  }

  public registerForPush() {
		//below code will throw an error if not running on a device
	  	 this.push.register().then((t: PushToken) => {
		  return this.push.saveToken(t, {ignore_user: true});
		 }).then((t: PushToken) => {
			  console.log(t.token);
	 		  let headers = new Headers();
	 		  headers.append("Content-Type","application/json");
	 		  let body = {
	 		  	token: t.token
	 		  };
	 		  //post device token to server, server url coming from secure tunnel to localhost generated by ngRok plugin
	 		 this.http.post("https://97de7914.ngrok.io/token", JSON.stringify(body), {headers: headers})
	 		  .map(res => res.json())
	 		  .subscribe(data => {
	 		  	console.log(data);
	 		  });
 		});

		this.push.rx.notification()
		  .subscribe((msg) => {
		    alert(/*msg.title + ': ' + */ msg.text);
		});}
}
