import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { Camera } from '@ionic-native/camera';
import { Http, Headers } from '@angular/http';
import { Observable } from 'rxjs/Observable';
/*
import {
  Push,
  PushToken
} from '@ionic/cloud-angular';
import { Http, Headers } from '@angular/http';
*/


@Component({
  selector: 'page-billsplitter',
  templateUrl: 'billsplitter.html'
})
export class BillSplitterPage {
public base64Image: string;
public camera: Camera;
  constructor(camera: Camera, public http: Http) {
    this.camera = camera;
  	//this.takePicture()
  }
uploadImage() {
  let headers = new Headers();
         headers.append("Content-Type","application/json");
         let body = {
           imageData: this.base64Image
         };
         //post device token to server, server url coming from secure tunnel to localhost generated by ngRok plugin
        this.http.post("http://ec2-13-59-35-127.us-east-2.compute.amazonaws.com:3000/api/imageAmount", JSON.stringify(body), {headers: headers})
         .map(res => res.json())
         .subscribe(data => {
           console.log(data);
         });
}
takePicture(){
    this.camera.getPicture({
        destinationType: this.camera.DestinationType.DATA_URL,
        targetWidth: 1000,
        targetHeight: 1000
    }).then((imageData) => {
      // imageData is a base64 encoded string
        this.base64Image = "data:image/jpeg;base64," + imageData;
        this.uploadImage();
    }, (err) => {
        console.log(err);
    });
  }
}
